import {loadData,fallback} from './data-loader.js';
const $=(selector,root=document)=>root.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeLink=value=>{const text=String(value||'');if(/^[a-z0-9-]+\.html(?:\?id=[a-z0-9-]+)?$/i.test(text))return text;try{const parsed=new URL(text);return parsed.protocol==='https:'?parsed.href:''}catch{return''}};
const safeImage=value=>/^images\/work\/[a-z0-9-]+\.(png|jpe?g|webp|gif)$/i.test(String(value||''))?value:'';
const date=value=>new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
const menu=$('.menu-button'),sidebar=$('.sidebar');
menu?.addEventListener('click',()=>{const open=!sidebar.classList.contains('open');sidebar.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''});
sidebar?.addEventListener('click',e=>{if(e.target.closest('a')&&innerWidth<=900){sidebar.classList.remove('open');menu?.setAttribute('aria-expanded','false');document.body.style.overflow=''}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&sidebar?.classList.contains('open')){sidebar.classList.remove('open');menu?.setAttribute('aria-expanded','false');document.body.style.overflow='';menu?.focus()}});
async function renderHome(){
  const projectsRoot=$('[data-projects]');if(projectsRoot){const projects=await loadData('projects.json',fallback.projects),homeOrder=p=>{const text=[p.id,p.title,p.category,...(p.technologies||[])].join(' ').toLowerCase();if(text.includes('collaboration')||text.includes('pin canvas')||text.includes('pincanvas'))return 2;if(text.includes('canva'))return 0;if(text.includes('google'))return 1;return 3},featured=projects.filter(p=>p.featured!==false).sort((a,b)=>(a.sortOrder||a.priority||999)-(b.sortOrder||b.priority||999)),ordered=[0,1,2].map(rank=>featured.find(p=>homeOrder(p)===rank)).filter(Boolean),homeProjects=[...ordered,...featured.filter(p=>!ordered.includes(p))].slice(0,3);projectsRoot.innerHTML=homeProjects.map((p,i)=>{const href=safeLink(p.detailUrl),image=safeImage(p.thumbnailUrl),label=(p.technologies||[]).slice(0,2).join(' / ')||p.category,number=String(i+1).padStart(2,'0');const content=`<div class="work-visual">${image?`<img src="${esc(image)}" alt="" loading="lazy">`:''}<span class="work-number">${number}</span><b>${esc(label)}</b><h3>${esc(p.title)}</h3></div><p>${esc(p.summary)}</p>`;return href?`<a class="work-card" href="${esc(href)}"${p.external?' target="_blank" rel="noopener noreferrer"':''}>${content}</a>`:`<article class="work-card">${content}</article>`}).join('');projectsRoot.querySelectorAll('.work-visual img').forEach(image=>image.addEventListener('error',()=>image.remove(),{once:true}))}
  const videosRoot=$('[data-videos]');if(videosRoot){const videos=await loadData('canva-videos.json',[]);if(!videos.length){videosRoot.innerHTML='<p class="status">새로운 Canva 콘텐츠를 준비 중입니다.</p>'}else{const [first,...rest]=videos;const thumbnail=first.thumbnailUrl?`<img src="${esc(first.thumbnailUrl)}" alt="" loading="lazy">`:'CANVA<br>FIELD NOTE';videosRoot.innerHTML=`<a class="featured-video" href="${esc(first.videoUrl)}" target="_blank" rel="noopener"><div class="video-thumb">${thumbnail}</div><div class="copy"><h3>${esc(first.title)}</h3><time datetime="${esc(first.publishedAt)}">${date(first.publishedAt)}</time><span>영상 보기 →</span></div></a><ul class="editorial-list">${rest.slice(0,3).map(v=>`<li><a href="${esc(v.videoUrl)}" target="_blank" rel="noopener"><time>${date(v.publishedAt)}</time><span>${esc(v.title)}</span><b>→</b></a></li>`).join('')}</ul>`;if(first.playlistId&&!first.playlistId.includes('PLACEHOLDER')){const link=$('[data-playlist-link]');link.href=`https://www.youtube.com/playlist?list=${encodeURIComponent(first.playlistId)}`;link.hidden=false}}}
  const lecturesRoot=$('[data-lectures]');if(lecturesRoot){const lectures=await loadData('lecture-history.json',[]);lecturesRoot.innerHTML=lectures.length?lectures.slice(0,4).map(l=>`<div class="lecture-row"><time datetime="${esc(l.date)}">${date(l.date)}</time><span>${esc(l.title)}</span><small>${esc(l.audience||l.organization||'')}</small></div>`).join(''):'<p class="status">공개 가능한 최근 강의 이력을 준비 중입니다.</p>'}
}
renderHome();
